const JWT_SECRET = process.env.JWT_SECRET || 'your_secret_key';
const AUTH_SERVICE_URL = process.env.AUTH_SERVICE_URL;
const TOUR_SERVICE_URL = process.env.TOUR_SERVICE_URL;
const BLOG_SERVICE_URL = process.env.BLOG_SERVICE_URL;
const FOLLOWER_SERVICE_URL = process.env.FOLLOWER_SERVICE_URL;
const STAKEHOLDER_SERVICE_URL = process.env.STAKEHOLDER_SERVICE_URL;

module.exports = {
  JWT_SECRET,
  AUTH_SERVICE_URL,
  TOUR_SERVICE_URL,
  BLOG_SERVICE_URL,
  FOLLOWER_SERVICE_URL,
  STAKEHOLDER_SERVICE_URL,
};