services:
  api-gateway:
    profiles: ["service"]
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    image: td-api-gateway
    container_name: td-api-gateway
    hostname: ${API_GATEWAY_HOST}
    environment:
      - PORT=${API_GATEWAY_PORT}
      - AUTH_SERVICE_URL=http://${AUTH_SERVICE_HOST}:${AUTH_SERVICE_PORT}
      - TOUR_SERVICE_URL=http://${TOUR_SERVICE_HOST}:${TOUR_SERVICE_PORT}
      - BLOG_SERVICE_URL=http://${BLOG_SERVICE_HOST}:${BLOG_SERVICE_PORT}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"

  auth-db:
    profiles: ["db"]
    image: postgres:16-alpine
    container_name: td-auth-db
    hostname: ${AUTH_DB_HOST}
    environment:
      - POSTGRES_DB=${AUTH_DB_NAME}
      - POSTGRES_USER=${AUTH_DB_USER}
      - POSTGRES_PASSWORD=${AUTH_DB_PASSWORD}
    ports:
      - "${AUTH_DB_EXT_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AUTH_DB_USER} -d ${AUTH_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  tour-db:
    profiles: ["db"]
    image: postgres:16-alpine
    container_name: td-tour-db
    hostname: ${TOUR_DB_HOST}
    environment:
      - POSTGRES_DB=${TOUR_DB_NAME}
      - POSTGRES_USER=${TOUR_DB_USER}
      - POSTGRES_PASSWORD=${TOUR_DB_PASSWORD}
    ports:
      - "${TOUR_DB_EXT_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TOUR_DB_USER} -d ${TOUR_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  follower-db:
    profiles: ["db"]
    image: neo4j:5.26-community
    container_name: td-follower-db
    hostname: ${FOLLOWER_DB_HOST}
    environment:
      - NEO4J_AUTH=${FOLLOWER_DB_USER}/${FOLLOWER_DB_PASSWORD}
      - NEO4J_dbms_default__database=${FOLLOWER_DB_NAME}
      #- NEO4J_dbms_connector_http_enabled=false  # Disable HTTP browser
      #- NEO4J_dbms_connector_https_enabled=false # Disable HTTPS browser
    ports:
      - "7474:7474"                                 # HTTP port (for Neo4j Browser)
      - "${FOLLOWER_DB_EXT_PORT}:7687"              # Bolt port
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u ${FOLLOWER_DB_USER} -p ${FOLLOWER_DB_PASSWORD} 'RETURN 1'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  blog-db:
    profiles: ["db"]
    image: mongo:7.0
    container_name: td-blog-db
    hostname: ${BLOG_DB_HOST}
    environment:
      - MONGO_INITDB_DATABASE=${BLOG_DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${BLOG_DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${BLOG_DB_PASSWORD}
    ports:
      - "${BLOG_DB_EXT_PORT}:27017"

  auth-service:
    profiles: ["service"]
    build:
      context: ./auth
      dockerfile: Dockerfile
    image: td-auth-service
    container_name: td-auth-service
    hostname: ${AUTH_SERVICE_HOST}
    environment:
      - PORT=${AUTH_SERVICE_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - AUTH_DB_HOST=${AUTH_DB_HOST}
      - AUTH_DB_PORT=5432
      - AUTH_DB_NAME=${AUTH_DB_NAME}
      - AUTH_DB_USER=${AUTH_DB_USER}
      - AUTH_DB_PASSWORD=${AUTH_DB_PASSWORD}
      - FOLLOWER_SERVICE_URL=http://${FOLLOWER_SERVICE_HOST}:${FOLLOWER_SERVICE_PORT}
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"

  follower-service:
    profiles: ["service"]
    build:
      context: ./follower
      dockerfile: Dockerfile
    image: td-follower-service
    container_name: td-follower-service
    hostname: ${FOLLOWER_SERVICE_HOST}
    environment:
      - PORT=${FOLLOWER_SERVICE_PORT}
      - FOLLOWER_DB_HOST=${FOLLOWER_DB_HOST}
      - FOLLOWER_DB_PORT=7687
      - FOLLOWER_DB_USER=${FOLLOWER_DB_USER}
      - FOLLOWER_DB_PASSWORD=${FOLLOWER_DB_PASSWORD}
    ports:
      - "${FOLLOWER_SERVICE_PORT}:${FOLLOWER_SERVICE_PORT}"

  tour-service:
    profiles: ["service"]
    build:
      context: ./tour
      dockerfile: Dockerfile
    image: td-tour-service
    container_name: td-tour-service
    environment:
      - PORT=${TOUR_SERVICE_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - TOUR_DB_HOST=${TOUR_DB_HOST}
      - TOUR_DB_PORT=5432
      - TOUR_DB_NAME=${TOUR_DB_NAME}
      - TOUR_DB_USER=${TOUR_DB_USER}
      - TOUR_DB_PASSWORD=${TOUR_DB_PASSWORD}
    ports:
      - "${TOUR_SERVICE_PORT}:${TOUR_SERVICE_PORT}"

  blog-service:
    profiles: ["service"]
    build:
      context: ./blog
      dockerfile: Dockerfile
    image: td-blog-service
    container_name: td-blog-service
    hostname: ${BLOG_SERVICE_HOST}
    environment:
      - PORT=${BLOG_SERVICE_PORT}
      - BLOG_DB_HOST=${BLOG_DB_HOST}
      - BLOG_DB_PORT=27017
      - BLOG_DB_NAME=${BLOG_DB_NAME}
      - BLOG_DB_USER=${BLOG_DB_USER}
      - BLOG_DB_PASSWORD=${BLOG_DB_PASSWORD}
    ports:
      - "${BLOG_SERVICE_PORT}:${BLOG_SERVICE_PORT}"

  seed:
    profiles: ["service"]
    build:
      context: ./seed
      dockerfile: Dockerfile
    image: td-seed
    container_name: td-seed
    environment:
      - AUTH_SERVICE_URL=http://${AUTH_SERVICE_HOST}:${AUTH_SERVICE_PORT}
      - FOLLOWER_SERVICE_URL=http://${FOLLOWER_SERVICE_HOST}:${FOLLOWER_SERVICE_PORT}
    depends_on:
      - auth-service
      - follower-service